title: inferi
tagline: the underworld computing
description: a group of friends writing about computer science and information security
url: https://inferi.club
lang: en
permalink: /blog/:slug/
future: true

collections:
  snippets:
    output: true
    permalink: /snippets/:slug/
  members:
    output: false

defaults:
  - scope:
      path: ""
      type: snippets
    values:
      layout: snippet

author:
  name: the inferi collective
  url: https://github.com/infericlub

social:
  github: https://github.com/infericlub
  twitter: https://x.com/infericlub
  rss: /feed.xml

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - CNAME

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - docs
  - .jekyll-cache
